$ANSIBLE_VAULT;1.1;AES256
39646265316666653265633232636432323761636366623936626534616566653236656631303439
3766376533343534393436323935663931636638303638630a393064383261306466356336366531
32353334396633373963303536313638643135646165366561343139636164653735353334376631
6166373565333033350a376631366266613838333538633535336662333661616663303865343332
36346263623233373030623264393263363131653234633264323461373631623637613436623232
64653134326161366532326434376633663330643430646432623430663639353534323835323464
61643338343534343530646238663137623436336261623266393965633161643639383331353333
35643062343330613161616161306563626534346137646235653432313666303338643064333937
37656638373661373461326137356661373665653033306662653164613462666432653136393738
30346664616266383438303166643739346237393037643930396530623534646634613238653431
64376436306139316432393434613133356139393766396366376463313339353733306231613765
66316330346334373435396332323762613832633461643862363838633366633163313639313761
30343436666533386465646262333937383236316234333334636433366561313962363364373534
35376636386332316166653630656238363738396536663639363935363536643332646466393064
32393434346232373931386538656533633031326132356339356232653365313436626263366238
61353636396230643362
